kustomize:
  images:
  - asia-south1-docker.pkg.dev/growthschool-core/demo-app/production-amd64=asia-south1-docker.pkg.dev/growthschool-core/demo-app/production-amd64:latest@sha256:8dc3706d63d4eea51099f9ce547cfeae092122738c95c4feef4d0a4cb672a011
